apiVersion: v1
kind: Service
metadata:
  name: get-hostname-service-001
spec:
  selector:
    app: get-hostname-001
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: NodePort


---
apiVersion: v1
kind: Pod
metadata:
  name: get-hostname-001
  labels:
    app: get-hostname-001
    ge-scheduler: global-01
spec:
  schedulerName: griffin_scheduler
  containers:
  - name: get-hostname-001
    image: dockereyes/get-hostname
    ports:
    - containerPort: 5000
